name: Frontend CI - Angular Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '19' 
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run Angular Unit Tests
      run: npx ng test --watch=false --browsers=ChromeHeadless

    - name: 'Notify Vercel'
      if: success()
      uses: 'vercel/repository-dispatch/actions/status@v1'
      with:
        name: 'Vercel - ims-frontend: Run Angular Unit Tests' # 需與後台設定名稱對應
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}