name: Frontend CI - Angular Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '19' 
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run Angular Unit Tests
      run: npx ng test --watch=false --browsers=ChromeHeadless

    - name: Trigger Vercel Deployment
      if: success() && github.ref == 'refs/heads/master'
      run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}&build_env=TRIGGERED_BY_ACTION=true"